[project]
name = "bluesky"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash>=3.2.0",
    "dash-bootstrap-components>=2.0.3",
    "highspy>=1.11.0",
    "matplotlib>=3.10.5",
    "networkx>=3.5",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "pyomo>=6.9.3",
    "sympy>=1.14.0",
    "toml>=0.10.2",
    "tomli>=2.2.1",
    "tomlkit>=0.13.3",
]


[tool.ruff]
line-length = 100
exclude = ['sample/hydrogen_interactive_dev','sample/integration_rebuild']

[tool.ruff.format]
quote-style = 'single'

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["unit_tests"]
log_file = "unit_tests/test_logs/testlog.log"
log_file_level = "INFO"


# these settings are for the linter which Pylance uses
# in VS Code.  Suppressing these avoids many warnings in pyomo-based code
# as pyomo isn't fully "typed", but still catches many others--a compromise.

[tool.pyright]
reportCallIssue = false
# reportArgumentType = false
reportOperatorIssue = false
reportOptionalMemberAccess = false
reportSelfClsParameterName = false
reportOptionalSubscript = false

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
